services:
  - type: web
    name: dashboard-ct-log
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_REQUIRED
        value: "1"
    disk:
      name: dashboard-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
